name: Create Rollic SDK Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  create-package:
    name: Create .unitypackage
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Generate a list of all .meta files for the SDK
      #    This is the crucial input for the packaging tool.
      - name: Generate meta file list
        run: find Assets/RollicSDK -name \*.meta > metaList.txt

      # 3. Create the output directory
      - name: Create Build Directory
        run: mkdir Build

      # 4. Use the lightweight action to create the .unitypackage
      - name: Create .unitypackage
        uses: pCYSl5EDgo/create-unitypackage@v1.2.3
        with:
          # The path where the final package will be saved
          package-path: 'Build/RollicSDK.unitypackage'

          # The text file containing the list of meta files to include
          include-files: 'metaList.txt'

      # 5. Upload the final package as a build artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RollicSDK-Package
          path: Build/RollicSDK.unitypackage
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    # This job needs permission to write to the gh-pages branch
    permissions:
      contents: write
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Doxygen and Graphviz on the runner
      - name: Install Doxygen & Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      # 3. Generate the documentation by running Doxygen
      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile

      # 4. Use a specialized action to deploy the HTML folder to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Documentation/html
   
